//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension API {

    /** Permite obter a informação standarizada de uma estação do Metro (coordenadas de GPS, URL, ID da estação,ect) */
    public enum GetInfoEstacaoByEstacao {

        public static let service = APIService<Response>(id: "getInfoEstacaoByEstacao", tag: "", method: "GET", path: "/infoEstacao/{estacao}", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** ID da Estação que pretende consultar, por exemplo, CG (Campo Grande), OD (Odivelas), etc. Pode obter a lista completa através da chamada /infoEstacao/todos */
                public var estacao: String

                public init(estacao: String) {
                    self.estacao = estacao
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetInfoEstacaoByEstacao.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(estacao: String) {
                let options = Options(estacao: estacao)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "estacao" + "}", with: "\(self.options.estacao)")
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = Void
            case status200

            public var success: Void? {
                switch self {
                case .status200: return ()
                }
            }

            public var response: Any {
                switch self {
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = .status200
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
